
version: '3'

services:

  inspire:
    image: yonh/inspire_flask
    container_name: inspire_flask
    restart: always
    environment:
      - SERVER_URL=192.168.66.66
    links:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: python3 ./inspire.py

  redis:
    restart: always
    image: redis:latest
    container_name: inspire_redis

  nginx:
    restart: always
    image: catone/inspire:nginx
    links:
      - inspire
    ports:
      - 9010:80
      - 80:81
    volumes:
      - /var/build:/var/build

    container_name: inspire_nginx
