# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  
  config.vm.provider "virtualbox" do |v|
    v.name = "ubuntu-18.04"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "256"
  end
end

